export const ActionTypes = {
    FETCH_PROPERTIES : 'FETCH_PROPERTIES',
    FETCH_BUY_PROPERTIES : 'FETCH_BUY_PROPERTIES',
    FETCH_RENT_PROPERTIES : 'FETCH_RENT_PROPERTIES',
    GET_PROPERTIES : "GET_PROPERTIES",
    SELECTED_PROPERTY : "SELECTED_PROPERTY",
    REMOVE_SELECTED_PROPERTY : "REMOVE_SELECTED_PROPERTY",
    ADD_PROPERTY : "ADD_PROPERTY",

    FETCH_USERS : 'FETCH_USERS',
    ADD_USER : "ADD_USER",
    ADD_USER_SUCCESS : "ADD_USER_SUCCESS",
    USER_LOGIN : "USER_LOGIN",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_AUTHENTICATION : "USER_AUTHENTICATION",
    USER_LOGOUT : "USER_LOGOUT",

    FETCH_INQUIRIES : "FETCH_INQUIRIES",
    SELECTED_INQUIRY : "SELECTED_INQUIRY",

} 